on: [workflow_dispatch]
name: Generate Outposts Data
jobs:
  generate_outposts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true

      - name: Git Submodule Update
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Run Outposts assetlists generation script
        run: pnpm run generate
      
      - name: Add Commit Push
        uses: devops-infra/action-commit-push@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          add_timestamp: false
          commit_prefix: "feat: [AUTO]"
          commit_message: "Outposts assetlist.json Update"
          force: false
          target_branch: update/assetlist

      - name: Create A PR
        uses: devops-infra/action-pull-request@v0.4.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: update/assetlist
          target_branch: main
          title: "Outposts assetlist.json Update"
          body: "**Automated pull request**"
          old_string: "**THIS IS AN AUTOMATED UPDATE OF OUTPOSTS ASSETLIST.JSON**"
          new_string: "** Automatic pull request**"
          get_diff: true
          ignore_users: "dependabot"